# Generated by Django 4.2 on 2025-08-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='message_accompagnement',
            field=models.TextField(blank=True, help_text='Message du client expliquant sa candidature pour ce projet', verbose_name="Message d'accompagnement"),
        ),
        migrations.AddField(
            model_name='document',
            name='motif_rejet',
            field=models.TextField(blank=True, help_text='Raison détaillée du rejet du document', verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='document',
            name='notes_admin',
            field=models.TextField(blank=True, help_text="Notes internes de l'administrateur", verbose_name='Notes administrateur'),
        ),
        migrations.AddField(
            model_name='document',
            name='traite_par',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a traité ce document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif de rejet (ancien)'),
        ),
    ]
