# Generated by Django 4.2.7 on 2025-08-14 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_customuser_options_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('document', 'Document'), ('project', 'Projet'), ('deadline', 'Échéance'), ('assignment', 'Assignation'), ('approval', 'Approbation'), ('warning', 'Avertissement'), ('info', 'Information'), ('success', 'Succès'), ('scraping', 'Données scrapées'), ('request', 'Demande client'), ('request_approved', 'Demande approuvée'), ('request_rejected', 'Demande rejetée')], max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message du client')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('in_progress', 'En cours de traitement')], default='pending', max_length=20, verbose_name='Statut')),
                ('client_info', models.JSONField(default=dict, verbose_name='Info client')),
                ('admin_response', models.TextField(blank=True, verbose_name='Réponse admin')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('priority_score', models.IntegerField(default=0, verbose_name='Score de priorité')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('projects', models.ManyToManyField(related_name='requests', to='main_app.scrapedproject', verbose_name='Projets demandés')),
            ],
            options={
                'verbose_name': 'Demande de projet',
                'verbose_name_plural': 'Demandes de projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='project_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main_app.projectrequest', verbose_name='Demande liée'),
        ),
    ]
