# Generated by Django 5.1.4 on 2025-08-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_notification_type_projectrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='original_source',
            field=models.CharField(blank=True, choices=[('GEF', 'Global Environment Facility'), ('GCF', 'Green Climate Fund'), ('OTHER', 'Autre source'), ('CLIMATE_FUND', 'Climate Funds Update')], max_length=15, verbose_name='Source originale'),
        ),
        migrations.AlterField(
            model_name='scrapedproject',
            name='source',
            field=models.CharField(choices=[('GEF', 'Global Environment Facility'), ('GCF', 'Green Climate Fund'), ('OTHER', 'Autre source'), ('CLIMATE_FUND', 'Climate Funds Update')], max_length=15, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='scrapingsession',
            name='source',
            field=models.CharField(choices=[('GEF', 'Global Environment Facility'), ('GCF', 'Green Climate Fund'), ('OTHER', 'Autre source'), ('CLIMATE_FUND', 'Climate Funds Update')], max_length=15, verbose_name='Source'),
        ),
    ]
