# Generated by Django 4.2 on 2025-08-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_notification_type_projectrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('source', models.CharField(choices=[('GEF', 'Global Environment Facility'), ('GCF', 'Green Climate Fund'), ('OTHER', 'Autre source')], max_length=10, verbose_name='Source')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL source')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('project_type', models.CharField(blank=True, max_length=200, verbose_name='Type de projet')),
                ('total_funding', models.CharField(blank=True, max_length=100, verbose_name='Financement total')),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant numérique')),
                ('country', models.CharField(default='Mauritania', max_length=100, verbose_name='Pays')),
                ('data_completeness_score', models.IntegerField(default=0, verbose_name='Score de complétude')),
                ('alert_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Alerte créée le')),
                ('is_new_this_week', models.BooleanField(default=True, verbose_name='Nouveau cette semaine')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('priority_level', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Niveau de priorité')),
                ('status', models.CharField(choices=[('active', 'Active'), ('read', 'Lue'), ('archived', 'Archivée'), ('dismissed', 'Ignorée')], default='active', max_length=20, verbose_name='Statut')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé le')),
                ('scraped_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='main_app.scrapedproject', verbose_name='Projet scrapé')),
            ],
            options={
                'verbose_name': 'Alerte de projet',
                'verbose_name_plural': 'Alertes de projets',
                'ordering': ['-alert_created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='project_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main_app.projectalert', verbose_name='Alerte liée'),
        ),
        migrations.AddIndex(
            model_name='projectalert',
            index=models.Index(fields=['status', 'alert_created_at'], name='main_app_pr_status_0e090c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectalert',
            index=models.Index(fields=['source', 'is_new_this_week'], name='main_app_pr_source_3bd56b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectalert',
            index=models.Index(fields=['priority_level', '-alert_created_at'], name='main_app_pr_priorit_2b486f_idx'),
        ),
    ]
