# Generated by Django 5.1.4 on 2025-08-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_project_original_source_and_more'),
        ('main_app', '0006_projectalert_notification_project_alert_and_more'),
    ]

    operations = [
    ]
