# Generated by Django 4.2.7 on 2025-07-26 14:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('level', models.CharField(choices=[('N1', 'Niveau 1'), ('N2', 'Niveau 2'), ('N3', 'Niveau 3'), ('N4', 'Niveau 4')], default='N1', max_length=2, verbose_name='Niveau')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('department', models.CharField(default='Financements Publics', max_length=100, verbose_name='Département')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_project', models.CharField(choices=[('etat', 'État'), ('prive', 'Privé : ONG / PME / Coopérative'), ('institution', 'Institution publique')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('progress', 'En cours'), ('ready', 'Prêt'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut')),
                ('fund', models.CharField(choices=[('GCF_SAP', 'GCF - Simplified Approval Process'), ('GCF_READINESS', 'GCF - Readiness Programme'), ('GEF_LDCF', 'GEF - Least Developed Countries Fund'), ('CIF', 'CIF - Climate Investment Funds')], max_length=30, verbose_name='Fonds')),
                ('score_viabilite', models.IntegerField(default=0, verbose_name='Score de viabilité')),
                ('montant_demande', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant demandé')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Nom du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du contact')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Consultant')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('project', 'Projet'), ('deadline', 'Échéance'), ('assignment', 'Assignation'), ('approval', 'Approbation'), ('warning', 'Avertissement'), ('info', 'Information'), ('success', 'Succès')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Consultant')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du fichier')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.documenttype', verbose_name='Type de document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main_app.project', verbose_name='Projet')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_soumission'],
                'unique_together': {('project', 'document_type')},
            },
        ),
    ]
