# Generated by Django 4.2.7 on 2025-07-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_scrapingsession_project_is_from_scraping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='scrapedproject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scrapedproject',
            name='unique_hash',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Hash unique'),
        ),
    ]
